### ISSUE TITLE
pls fix rendu3j_psychedelic.s

### ISSUE THREAD

**Issue by little-nem** [Simpfally/ASR#9]
it does not 
WORK

**Comment by vmerckle** [comment]
IT IS NOT MY RESPONSABILITY
CALLING IN @Potatoe37

**Comment by little-nem** [comment]
I'm soooooooooooo impatient to see some good psychedelic dope

**Comment by vmerckle** [comment]
https://www.google.fr/search?safe=off&client=firefox-b-ab&dcr=0&biw=1916&bih=970&tbm=isch&sa=1&ei=OBBiWqmwJJD8kwX9zKII&btnG=Rechercher&q=psyhcjdelic

THERE U GO
FIXED
NEXT!
